# add user in router
# /user add address=10.130.11.57/32 group=read name=diff password=XXXXXXXXXXX



[router1]
host = 10.130.11.1
username = diff
password = XXXXXXXXXXX

[router2]
host = 10.130.11.2
username = diff
password = XXXXXXXXXXX

[general]
method = ssh

[files]
old_config = router1_config.rsc
new_config = router2_config.rsc
output_diff = diff_output.txt

