# add user in router
# /user add address=10.40.134.57/32 group=read name=diff password=Fewfnejkjn2k3fn



[router1]
host = 10.130.11.1
username = diff
password = Fewfnejkjn2k3fn

[router2]
host = 10.130.11.2
username = diff
password = Fewfnejkjn2k3fn

[general]
method = ssh

[files]
old_config = router1_config.rsc
new_config = router2_config.rsc
output_diff = diff_output.txt

